### ISSUE TITLE
[Помогите] Похоже, что моды не загружаются! 

### ISSUE THREAD

**Issue by FX0x00F** [CallowBlack/MCSkill-ModLoader#1]
Привет! Спасибо за твою прекрасную программу, однако у меня возникло несколько вопросов:

1. В README написано что создается файл _customLauncher.ini_ , и да, он правда создается, но где должна быть папка _customMods_ и файл _customMods.json_ - не совсем понятно. Лично я создал эту папку и файл там же, где лежит _<файл_релиза>_ и _customLauncher.ini_ . Пример: вот как это выглядит у меня: [Скриншот](https://prnt.sc/1053nsr) Правильно ли это?
2. Допустим, я все сделал правильно. Затем я поместил необходимый мне мод в папку _customMods_ . Пусть например это будет как на скриншоте: [Скриншот](https://prnt.sc/1053rjr). После чего настроил json файл следующим образом: [json](https://prnt.sc/1053t51). Вопрос: на этом шаге всё пока-что правильно?
3. После чего я запускаю как было сказано. На текущий момент времени это так: _java -jar MCSkillStarter.v1.3.jar_ . Я поставил в настройках режим дебага, и вот что он мне выдает, когда я нажимаю в лаунчере "играть"  [Дебаг](https://prnt.sc/10540e8). После захода на сервер никакой мод из тех, что я планировал добавить не работает. Хотя версия сборки подходит. Есть варианты, что может быть не так?
Заранее спасибо! Надеюсь, вы поможете мне решить эту проблему.

**Comment by FX0x00F** [comment]
Было бы особенно неплохо если бы вы еще сказали, поддерживаются ли моды в .dll формате, а так же было бы замечательно если бы поделились готовой сборкой (я имею ввиду с папкой _customMods _ ) и настройками. Спасибо!

**Comment by CallowBlack** [comment]
1. _customMods.json_ - должен находится в папке с файлами майнкрафта, у меня например `%appdata%/McSkill/updates`. При нормальной работе программы он создастся автоматически при первом запуске программы. Сам стартер не обязательно туда помещать.
2. Не совсем правильно, сами моды должны находится в блоке _includeMods_. Однако это не было написано в README, я обновлю её.
3. Похоже проблема с самой программой, возможно обновили клиент.

**Comment by CallowBlack** [comment]
Похоже привязываться к номеру билда было плохой идеей. Лаунчер обновили, хотя и номер не поменяли, поэтому весь функционал накрылся. Я постараюсь обновить до новой версии.

**Comment by CallowBlack** [comment]
Обновил, вам же советую удалить тот файл  _customMods.json_ который вы самостоятельно создали, пусть сама программа это сделает + там будут примеры использования. В моём случае [_customMods.json_ выглядит так](https://pastebin.com/TetgEZci), [директория updates - так](https://ibb.co/qM2mMGJ), [директория customMods - так](https://ibb.co/vJ13Nxr).

**Comment by CallowBlack** [comment]
> 
> 
> Было бы особенно неплохо если бы вы еще сказали, поддерживаются ли моды в .dll формате, а так же было бы замечательно если бы поделились готовой сборкой (я имею ввиду с папкой _customMods _ ) и настройками. Спасибо!

Данная программа не будет поддерживать dll файлы, только .jar моды. По большинству все dll файлы содержат в себе jar с модом, так что можете попытаться его достать.

**Comment by FX0x00F** [comment]
Кем бы ты ни был, ты крутой! Проверил. Все работает. Правда нужно быть аккуратным, на некоторых серверах правда могут забанить. Однозначно подписка и звездочка на гите) Молодец! Спасибо. Закрываю вопрос.
