### ISSUE TITLE
кста

### ISSUE THREAD

**Issue by levshx** [CallowBlack/MCSkill-ModLoader#2]
Можно спокойно делать свой клиент на 1.7.10 с читами, разраб лаунчера забыл убрать из режима отладки токен для онлайна, получаешь токен, запускаешь свой лаунчер, играешь с читами, вопрос только в том, чтобы скрыть из списка модов мод с читами (( они отправляются (список установленных модов) на сервер, а далее пишутся в логи.

Токен действует 24 часа

На проекте кстати действует мод со скриншотом игроков

Вот пример открытых аргументов запуска которые можно воровать

`2021.03.01 20:41:41 [DEBUG] Args: [--username, levshx, --uuid, *******83d#####e3efdb7*****b6789967a2, --accessToken, ###########aa4b2b455*******103, --userType, mojang, --userProperties, {"skinURL":["https://skins.mcskill.ru/MinecraftSkins/levshx.png"],"skinDigest":["52622367e8843a84b****************************17ecf1ea0"],"cloakURL":["https://skins.mcskill.ru/MinecraftCloaks/levshx.png"],"cloakDigest":["7b78d41030ba####################################0d008a7f464a0e"]}, --assetIndex, 1.7.10, --version, 1.7.10, --gameDir, C:\Users\Pavel\AppData\Roaming\McSkill\updates\TechnoMagic_1.7.10, --assetsDir, C:\Users\Pavel\AppData\Roaming\McSkill\updates\asset1.7.10, --resourcePackDir, C:\Users\Pavel\AppData\Roaming\McSkill\updates\TechnoMagic_1.7.10\resourcepacks, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, com.mumfrey.liteloader.launch.LiteLoaderTweaker]`

**Comment by CallowBlack** [comment]
Про отправление на сервер, из оффициальных способов я знаю только отправление через _handshake_ при подключении, функционал исключения своего мода из отправки в этом пакете уже есть.

**Comment by CallowBlack** [comment]
Про собственный клиент - да, возможно подменить их клиент на свой, но для этого нужно будет изменить клиент, чтобы он корректно себя вёл при подключении к серверу, например отправлял токен. Это как по мне уже лишняя работа.

**Comment by CallowBlack** [comment]
А теперь непосредственно на счёт античита.  Я не уверен, что данные отправляются именно через добавленный функционал в клиент, а не через моды, потому, как на 1.12.2 изменить клиент, статически (через файл), весьма проблематично по сравнению с 1.12.2, но там так же находят запущенные моды. Так, что я вижу только 2 варианта - либо они изменяют клиент, перед запуском через лаунчер, с помощью того же javassist или, они просто добавили мод который это делает.

**Comment by CallowBlack** [comment]
Про мод который делает скриншоты игры, я его тоже видел, но этот мод скорее для проверки модерами игроков, а не для автоматического бана. Его можно тоже переписать, но так как я достаточно слаб в работе с OpenGL, я пока этим заниматься не буду.

**Comment by CallowBlack** [comment]
Закрываю предложение :)
